version: '3.7'

services:
  reverse-proxy:
    image: traefik:latest
    restart: always
    container_name: traefik

    env_file:
      - cloudflare.env

    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
    networks:
      - external
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik.toml:/traefik.toml
      - acme.json:/acme.json
    labels:
      - 'traefik.backend=traefik'
      - 'traefik.docker.network=external'
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:traefik.foo.com'
      - 'traefik.port=8080'
      - 'traefik.frontend.headers.forceSTSHeader=true'
      - 'traefik.frontend.headers.STSSeconds=315360000'
      - 'traefik.frontend.headers.STSIncludeSubdomains=true'
      - 'traefik.frontend.headers.STSPreload=true'

networks:
  external:
    external: true